### ISSUE TITLE
Massive console spam when with corail-tombstone.

### ISSUE THREAD

**Issue by batlham** [baguchan/EarthMobs#30]
EarthMobs-1.19.2-4.2.0
I get an excessive amount of console spam and the lag with it when installed with corail-tombstone
https://www.curseforge.com/minecraft/mc-mods/corail-tombstone

The message is [00:01:46] [Server thread/INFO] [tombstone/]: A mod is doing something strange in LivingEntity.getMobType()
Either mod without the other has no message.

I figure is has to do with changes to getMobType.
https://github.com/baguchan/EarthMobs/blob/1.19/src/main/java/baguchan/earthmobsmod/mixin/LivingEntityMixin.java#L26

corail-tombstone makes no changes to getMobType.

**Comment by baguchan** [comment]
thanks for the easy to understand explanation!
I will fix it in the next update of 1.19.3
1.19.2 may not be fixed due to the repository
sorry about that....
Please let me know if you get the same error again in 1.19.3

**Comment by Corail31** [comment]
@baguchan Hi Bagu, glad to see you are still modding since The Midnight mod ;) Could you take a look to fix version 1.19.2 which is probably more used than 1.19.3? Thank you. (I could remove my log but i would prefer to remove my 'try catch')

**Comment by mrcalzon02** [comment]
it would be appreciated if 1> the error could be fixed in a update for 1.19.2 compatible version of Earth Mobs, OR Tombstone Could Not call an endless log flood. with a simple check to detect if the error has already been detected. ether option would be nice, In the mean time which Version of Tombstone doesn't have the  mixin  'try catch'? so people might use that in the time till a choice is made.

**Comment by baguchan** [comment]
@Corail31 sorry for late.
will try to fix it later!
also thank you for finding me ;)

**Comment by baguchan** [comment]
fixed!
If still happen. let's me know!
https://github.com/baguchan/EarthMobs/commit/d1c4064575e6cf1bd08f36fcef9e8802116fe76a
